name: pummel_the_fish
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: "3.19.2"

dependencies:
  collection: ^1.17.1
  font_awesome_flutter: ^10.7.0
  flutter:
    sdk: flutter
  http: ^1.6.0
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/